// Renders the certification report as Markdown and as a single-file HTML page.
// Status colours follow a fixed status palette and are never the only carrier of
// meaning (icon + label always accompany them).

const ICON = { PASS: '✔', WARN: '▲', FAIL: '✖', SKIP: '–' };
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const secs = (ms) => (ms == null ? '—' : `${(ms / 1000).toFixed(1)}s`);
const pct = (v) => (Number.isFinite(v) ? `${(v * 100).toFixed(2)}%` : '—');

export function verdictOf(r) {
  const all = [...r.conformance, ...r.synthetic, ...r.chaos];
  if (all.some(x => x.status === 'FAIL')) return 'FAIL';
  if (all.some(x => x.status === 'WARN')) return 'WARN';
  return 'PASS';
}

function counts(list) {
  const c = { PASS: 0, WARN: 0, FAIL: 0, SKIP: 0 };
  for (const x of list) c[x.status] = (c[x.status] || 0) + 1;
  return c;
}

// ------------------------------------------------------------------ Markdown
export function renderMarkdown(r) {
  const v = verdictOf(r);
  const L = [];
  L.push(`# IBM MQ Observability Certification Report`);
  L.push('');
  L.push(`**Verdict: ${ICON[v]} ${v}** — pack \`${r.pack.metadata.name}@${r.pack.metadata.version}\` (spec ${r.pack.apiVersion}), run ${r.startedAt} → ${r.finishedAt} (${secs(r.durationMs)})`);
  L.push('');
  L.push(`| Suite | PASS | WARN | FAIL | SKIP |`);
  L.push(`|---|---:|---:|---:|---:|`);
  for (const [name, list] of [['Conformance', r.conformance], ['Synthetic', r.synthetic], ['Chaos', r.chaos]]) {
    const c = counts(list); L.push(`| ${name} | ${c.PASS} | ${c.WARN} | ${c.FAIL} | ${c.SKIP} |`);
  }
  L.push('');
  L.push(`## Environment`);
  L.push('');
  L.push(`| Service | Image | State |`);
  L.push(`|---|---|---|`);
  for (const s of r.environment.services) L.push(`| ${s.service} | \`${s.image}\` | ${s.state} |`);
  L.push('');
  L.push(`## 1. Conformance — does the stack implement the pack?`);
  L.push('');
  L.push(`| # | Check | Result | Detail |`);
  L.push(`|---|---|---|---|`);
  for (const c of r.conformance) L.push(`| ${c.id} | ${c.title} | ${ICON[c.status]} ${c.status} | ${c.detail} |`);
  L.push('');
  const c3 = r.conformance.find(c => c.id === 'C3');
  if (c3?.evidence?.length) {
    L.push(`### SLI values at certification time`);
    L.push('');
    L.push(`| SLI | Type | Value | Threshold | Unit |`);
    L.push(`|---|---|---:|---:|---|`);
    for (const s of c3.evidence) L.push(`| \`${s.id}\` | ${s.type} | ${s.value == null ? '—' : (s.type === 'ratio' ? pct(s.value) : Number(s.value).toPrecision(4))} | ${s.threshold ?? '—'} | ${s.unit} |`);
    L.push('');
  }
  L.push(`## 2. Synthetic — is the canary / orders flow healthy?`);
  L.push('');
  L.push(`| # | Check | Result | Detail |`);
  L.push(`|---|---|---|---|`);
  for (const c of r.synthetic) L.push(`| ${c.id} | ${c.title} | ${ICON[c.status]} ${c.status} | ${c.detail} |`);
  L.push('');
  L.push(`## 3. Chaos — do the alerts fire, in time, and resolve?`);
  L.push('');
  if (!r.chaos.length) L.push(`_Chaos suite skipped for this run._`);
  for (const x of r.chaos) {
    L.push(`### ${ICON[x.status]} ${x.status} — \`${x.id}\` (target: ${x.target}, SLO: \`${x.slo}\`)`);
    L.push('');
    L.push(`Fault \`${JSON.stringify(x.fault)}\` injected ${x.injectedAt ?? '—'}, recovered ${x.recoveredAt ?? '—'}. SLI before/during/after: ${fmtSli(x.sliBefore)} / ${fmtSli(x.sliDuring)} / ${fmtSli(x.sliAfter)}.`);
    L.push('');
    L.push(`| Expected alert | Fired | MTTD | Target | Resolved after recovery |`);
    L.push(`|---|---|---:|---:|---:|`);
    for (const a of x.alerts) L.push(`| ${a.alertname} | ${a.fired ? 'yes' : '**no**'} | ${secs(a.mttdMs)} | ${secs(x.expectedMttdMs)} | ${secs(a.resolvedAfterMs)} |`);
    if (x.others?.length) L.push(`\nAlso fired during the fault: ${x.others.map(o => `\`${o}\``).join(', ')}`);
    if (x.notes?.length) L.push(`\nNotes: ${x.notes.join('; ')}`);
    L.push('');
  }
  L.push(`## 4. Pack summary`);
  L.push('');
  L.push(`| SLO | SLI | Objective | Window |`);
  L.push(`|---|---|---:|---|`);
  for (const s of r.pack.spec.slos) L.push(`| \`${s.id}\` | \`${s.sli}\` | ${s.objective} | ${s.window} |`);
  L.push('');
  L.push(`Baselines: MTTD p50/p95 ${r.pack.spec.baselines.mttd_target_p50}/${r.pack.spec.baselines.mttd_target_p95}, MTTR p50/p95 ${r.pack.spec.baselines.mttr_target_p50}/${r.pack.spec.baselines.mttr_target_p95}. Measured chaos MTTD p50/p95 this run: ${secs(r.mttd.p50)} / ${secs(r.mttd.p95)} over ${r.mttd.n} alert detections.`);
  L.push('');
  L.push(`---`);
  L.push(`Generated by \`harness/run.mjs\` — raw evidence in \`cert-report.json\`.`);
  return L.join('\n') + '\n';
}

const fmtSli = (v) => (v == null || Number.isNaN(v) ? '—' : Number(v).toPrecision(3));

// ---------------------------------------------------------------------- HTML
export function renderHtml(r) {
  const v = verdictOf(r);
  const badge = (s) => `<span class="badge ${s.toLowerCase()}"><span aria-hidden="true">${ICON[s]}</span> ${s}</span>`;
  const rows = (list) => list.map(c => `<tr><td class="mono">${esc(c.id)}</td><td>${esc(c.title)}</td><td>${badge(c.status)}</td><td>${esc(c.detail)}</td></tr>`).join('');
  const c3 = r.conformance.find(c => c.id === 'C3');
  const maxMttd = Math.max(1, ...r.chaos.flatMap(x => [x.expectedMttdMs, ...x.alerts.map(a => a.mttdMs || 0)]));

  const chaosHtml = r.chaos.length ? r.chaos.map(x => `
    <section class="card">
      <h3>${badge(x.status)} <code>${esc(x.id)}</code> <span class="muted">target ${esc(x.target)} · SLO <code>${esc(x.slo)}</code></span></h3>
      <p class="muted">Fault <code>${esc(JSON.stringify(x.fault))}</code> · injected ${esc(x.injectedAt)} · recovered ${esc(x.recoveredAt)} · SLI before/during/after ${fmtSli(x.sliBefore)} / ${fmtSli(x.sliDuring)} / ${fmtSli(x.sliAfter)}</p>
      <table><thead><tr><th>Expected alert</th><th>Fired</th><th>MTTD vs target (${secs(x.expectedMttdMs)})</th><th>Resolved after recovery</th></tr></thead><tbody>
      ${x.alerts.map(a => `<tr><td class="mono">${esc(a.alertname)}</td><td>${a.fired ? 'yes' : '<strong>no</strong>'}</td>
        <td><div class="bar" title="MTTD ${secs(a.mttdMs)} · target ${secs(x.expectedMttdMs)}"><div class="fill ${a.fired ? (a.withinTarget ? 'ok' : 'late') : 'none'}" style="width:${a.mttdMs ? Math.min(100, a.mttdMs / maxMttd * 100) : 0}%"></div><div class="target" style="left:${Math.min(100, x.expectedMttdMs / maxMttd * 100)}%"></div></div><span class="mono">${secs(a.mttdMs)}</span></td>
        <td class="mono">${secs(a.resolvedAfterMs)}</td></tr>`).join('')}
      </tbody></table>
      ${x.others?.length ? `<p class="muted">Also fired during the fault: ${x.others.map(o => `<code>${esc(o)}</code>`).join(', ')}</p>` : ''}
      ${x.notes?.length ? `<p class="note">${esc(x.notes.join('; '))}</p>` : ''}
    </section>`).join('') : '<p class="muted">Chaos suite skipped for this run.</p>';

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>IBM MQ Observability Certification</title>
<style>
:root{color-scheme:light;--surface:#fcfcfb;--page:#f9f9f7;--ink:#0b0b0b;--ink-2:#52514e;--muted:#898781;--grid:#e1e0d9;--ring:rgba(11,11,11,.10);--series:#2a78d6;--good:#0ca30c;--warn:#fab219;--crit:#d03b3b;--good-text:#006300}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){color-scheme:dark;--surface:#1a1a19;--page:#0d0d0d;--ink:#fff;--ink-2:#c3c2b7;--grid:#2c2c2a;--ring:rgba(255,255,255,.10);--series:#3987e5;--good-text:#0ca30c}}
:root[data-theme=dark]{color-scheme:dark;--surface:#1a1a19;--page:#0d0d0d;--ink:#fff;--ink-2:#c3c2b7;--grid:#2c2c2a;--ring:rgba(255,255,255,.10);--series:#3987e5;--good-text:#0ca30c}
*{box-sizing:border-box}body{margin:0;background:var(--page);color:var(--ink);font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
main{max-width:1100px;margin:0 auto;padding:32px 16px}h1{font-size:26px;margin:0 0 4px}h2{font-size:19px;margin:36px 0 12px}h3{font-size:16px;margin:0 0 6px}
.muted{color:var(--ink-2);font-weight:400}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:13px}code{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px}
.card{background:var(--surface);border:1px solid var(--ring);border-radius:10px;padding:16px;margin:12px 0}
table{width:100%;border-collapse:collapse;background:var(--surface)}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--grid);vertical-align:top}th{color:var(--ink-2);font-weight:600;font-size:13px}
.badge{display:inline-flex;gap:6px;align-items:center;padding:2px 9px;border-radius:999px;font-size:12px;font-weight:600;border:1px solid var(--ring);white-space:nowrap}
.badge.pass{color:var(--good-text);background:color-mix(in srgb,var(--good) 14%,transparent)}.badge.warn{color:var(--ink);background:color-mix(in srgb,var(--warn) 30%,transparent)}.badge.fail{color:#fff;background:var(--crit)}.badge.skip{color:var(--ink-2)}
.hero{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:20px 0}.tile{background:var(--surface);border:1px solid var(--ring);border-radius:10px;padding:14px}.tile .k{font-size:12px;color:var(--ink-2)}.tile .v{font-size:26px;font-weight:700;margin-top:4px}
.bar{position:relative;height:10px;background:var(--grid);border-radius:4px;margin:6px 0 2px;min-width:180px}.fill{height:100%;border-radius:4px;background:var(--series)}.fill.late{background:var(--warn)}.fill.none{background:transparent}.target{position:absolute;top:-3px;width:2px;height:16px;background:var(--ink)}
.note{color:var(--ink-2);font-style:italic}footer{margin-top:40px;color:var(--muted);font-size:13px}
@media (max-width:640px){table{display:block;overflow-x:auto}}
</style></head><body><main>
<h1>IBM MQ Observability Certification</h1>
<p class="muted">Pack <code>${esc(r.pack.metadata.name)}@${esc(r.pack.metadata.version)}</code> · ${esc(r.pack.apiVersion)} · run ${esc(r.startedAt)} → ${esc(r.finishedAt)} (${secs(r.durationMs)}) · host ${esc(r.environment.host)}</p>
<div class="hero">
  <div class="tile"><div class="k">Verdict</div><div class="v">${badge(v)}</div></div>
  <div class="tile"><div class="k">Conformance</div><div class="v">${counts(r.conformance).PASS}/${r.conformance.length} <span class="muted" style="font-size:13px">pass</span></div></div>
  <div class="tile"><div class="k">Synthetic</div><div class="v">${counts(r.synthetic).PASS}/${r.synthetic.length} <span class="muted" style="font-size:13px">pass</span></div></div>
  <div class="tile"><div class="k">Chaos</div><div class="v">${counts(r.chaos).PASS}/${r.chaos.length} <span class="muted" style="font-size:13px">pass</span></div></div>
  <div class="tile"><div class="k">Measured MTTD p50 / p95</div><div class="v">${secs(r.mttd.p50)} <span class="muted" style="font-size:13px">/ ${secs(r.mttd.p95)}</span></div></div>
</div>

<h2>Environment</h2>
<table><thead><tr><th>Service</th><th>Image</th><th>State</th></tr></thead><tbody>${r.environment.services.map(s => `<tr><td>${esc(s.service)}</td><td class="mono">${esc(s.image)}</td><td>${esc(s.state)}</td></tr>`).join('')}</tbody></table>

<h2>1. Conformance — does the stack implement the pack?</h2>
<table><thead><tr><th>#</th><th>Check</th><th>Result</th><th>Detail</th></tr></thead><tbody>${rows(r.conformance)}</tbody></table>
${c3?.evidence?.length ? `<h3 style="margin-top:16px">SLI values at certification time</h3>
<table><thead><tr><th>SLI</th><th>Type</th><th>Value</th><th>Threshold</th><th>Unit</th></tr></thead><tbody>${c3.evidence.map(s => `<tr><td class="mono">${esc(s.id)}</td><td>${esc(s.type)}</td><td class="mono">${s.value == null ? '—' : (s.type === 'ratio' ? pct(s.value) : esc(Number(s.value).toPrecision(4)))}</td><td class="mono">${esc(s.threshold ?? '—')}</td><td>${esc(s.unit)}</td></tr>`).join('')}</tbody></table>` : ''}

<h2>2. Synthetic — is the canary / orders flow healthy?</h2>
<table><thead><tr><th>#</th><th>Check</th><th>Result</th><th>Detail</th></tr></thead><tbody>${rows(r.synthetic)}</tbody></table>

<h2>3. Chaos — do the alerts fire, in time, and resolve?</h2>
<p class="muted">Bar = measured MTTD (alert-sink receipt − injection); tick = pack target. Blue within target, amber late.</p>
${chaosHtml}

<h2>4. Pack summary</h2>
<table><thead><tr><th>SLO</th><th>SLI</th><th>Objective</th><th>Window</th></tr></thead><tbody>${r.pack.spec.slos.map(s => `<tr><td class="mono">${esc(s.id)}</td><td class="mono">${esc(s.sli)}</td><td class="mono">${esc(s.objective)}</td><td>${esc(s.window)}</td></tr>`).join('')}</tbody></table>
<p class="muted">Baselines: MTTD p50/p95 ${esc(r.pack.spec.baselines.mttd_target_p50)}/${esc(r.pack.spec.baselines.mttd_target_p95)} · MTTR p50/p95 ${esc(r.pack.spec.baselines.mttr_target_p50)}/${esc(r.pack.spec.baselines.mttr_target_p95)} · regression gate <code>${esc(r.pack.spec.baselines.regression_gate)}</code></p>

<footer>Generated by <code>harness/run.mjs</code>. Raw evidence (every query result, every webhook event) is in <code>cert-report.json</code> next to this file.</footer>
</main></body></html>`;
}
